# Generated by Django 4.2.7 on 2023-11-23 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('phone', models.IntegerField(max_length=10)),
            ],
        ),
    ]
