# Generated by Django 4.2.7 on 2023-11-23 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add',
            name='phone',
        ),
    ]
